name: tkty

on:
  schedule:
    - cron: '*/15 12-15 * * *'
    - cron: '*/15 0-2 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install selenium requests futures eventlet

      - name: Run tkty
        run: python ${{ github.workspace }}/tkty.py

      - name: 提交更改
        run: |
          git config --local user.email "limiaobj@hotmail.com"
          git config --local user.name "outcastveron"
          git add .
          git commit *.txt -m "Add generated file"
          git commit *.m3u -m "Add generated file"
          #git pull --rebase
          git push -f
